# Generated by Django 6.0.3 on 2026-03-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('date_of_admission', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
